[phases.build]
dependsOn = ["install"]
cmd = ["./cmd/nixpacks/build.sh"]

[phases.install]
dependsOn = ["setup"]
cmd = "./cmd/nixpacks/install.sh"

[phases.setup]
nixPkgs = [
    'python310',
    'gcc',
]
nixLibs = [
    'zlib',
    'stdenv.cc.cc.lib',
]
nixOverlays = []
nixpkgsArchive = '293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847'

[start]
cmd = "python -OO -m bot"
