import os

GATEWAY_BOT_TOKEN = os.environ.get("GATEWAY_BOT_TOKEN")

JAVA_SERVER_HOST = os.environ.get("JAVA_SERVER_HOST")
JAVA_SERVER_PORT = os.environ.get("JAVA_SERVER_PORT")

PRIVATE_VOICE_CHANNEL_GUILD_ID = os.environ.get("PRIVATE_VOICE_CHANNEL_GUILD_ID")
PRIVATE_VOICE_CHANNEL_CATEGORY_ID = os.environ.get("PRIVATE_VOICE_CHANNEL_CATEGORY_ID")
